version: '3.8'

services:
    app: # ✅ 반드시 services 밑에 있어야 함
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - db
        env_file:
            - .env
        volumes:
            - .:/app

    db:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: 1212
            MYSQL_DATABASE: eduRunDB
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
