version: '3.8'

services:
    app:
        build: .
        ports:
            - '3000:3000' # ❌ "80:3000"처럼 80포트 매핑하지 마세요
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro # 인증서 읽기 전용 공유
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: mariadb:10.5
        environment:
            MYSQL_ROOT_PASSWORD: 1212
            MYSQL_DATABASE: eduRunDB
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
