version: '3.8'

services:
    app:
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - mariadb
        environment:
            DB_HOST: mariadb
            DB_USER: root
            DB_PASSWORD: rootpw
            DB_NAME: mydb
        volumes:
            - .:/app
            - /app/node_modules

    mariadb:
        image: mariadb:10.5
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: rootpw
            MARIADB_DATABASE: mydb
        ports:
            - '3306:3306'
